CREATE TABLE IF NOT EXISTS ACCOUNT
(
    ID NUMBER (20) IDENTITY PRIMARY KEY ,
    LOGIN VARCHAR(100) UNIQUE NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL,
    BALANCE DECIMAL DEFAULT 0
);

CREATE SEQUENCE IF NOT EXISTS ACCOUNT_SEQUENCE;

CREATE INDEX IF NOT EXISTS ACCOUNT_LOGIN_INX ON ACCOUNT(LOGIN);